name: powershell-sandbox-directory-steps
version: 1.0.0
rundeckPluginVersion: 1.2
author: Rundeck
date: Tue Dec 12 2017
providers:
  - name: powershell-sandbox-directory-create
    service: RemoteScriptNodeStep
    title: 'Powershell / Sandbox / Create'
    description: 'Create sandbox directory'
    plugin-type: script
    script-interpreter: "powershell -NonInteractive -Noprofile -ExecutionPolicy Bypass -Command"
    script-file: Sandbox-Create.ps1
    script-args: "-Destination ${config.destination} -Ident ${config.ident} -Print ${config.print}"
    config:
      - type: String
        name: destination
        title: destination
        description: 'the path for the temporary directory'
        required: true
        default: $env:USERPROFILE
      - type: String
        name: ident
        title: 'The identity string'
        default: ${job.execid}
        required: true
      - type: Boolean
        name: print
        title: Print Sandbox for data capture
        default: true
        description: 'Print Sandbox folder on Data-Capture format'
  - name: powershell-sandbox-directory-delete
    service: RemoteScriptNodeStep
    title: 'Powershell / Sandbox / Delete'
    description: 'Delete sandbox directory'
    plugin-type: script
    script-interpreter: "powershell -NonInteractive -Noprofile -ExecutionPolicy Bypass -Command"
    script-file: Sandbox-Delete.ps1
    script-args: "-Destination ${config.destination} -Ident ${config.ident}"
    config:
      - type: String
        name: destination
        title: destination
        description: 'the path for the temporary directory'
        required: true
        default: $env:USERPROFILE
      - type: String
        name: ident
        title: 'The identity string'
        default: ${job.execid}
        required: true
